version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "dependabot"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
      timezone: "Asia/Tokyo"
