version: "3"

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - "..:/app:cached"
    tty: true

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo

  redis:
    image: redis:latest
    volumes:
      - redis:/data

volumes:
  mysql-data:
  redis:
